name: Build Geode Mod

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: geode-sdk/geode-actions/.github/workflows/build.yml@main
    with:
      loader-version: v3.0.0
      
